//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PcShare.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_PCSHARTYPE                  129
#define ID_FRAME_INFO                   129
#define IDD_DIALOG_AINIMA               130
#define IDC_CURSOR_LOGO                 131
#define IDC_CURSOR_WAIT                 132
#define IDI_ICON_COMPUTER               134
#define IDB_BITMAP1                     137
#define IDB_BITMAP2                     138
#define IDB_BITMAP3                     139
#define IDB_BITMAP4                     140
#define IDB_BITMAP5                     141
#define IDB_BITMAP6                     142
#define IDB_BITMAP7                     143
#define IDB_BITMAP8                     144
#define IDB_BITMAP9                     145
#define IDB_BITMAP10                    146
#define IDB_BITMAP11                    147
#define IDB_BITMAP12                    148
#define IDB_BITMAP13                    156
#define IDD_DIALOG_SETUP                157
#define IDD_DIALOG_CREATE_CLIENT        158
#define IDI_ICON_EVENT_NORMAL           159
#define IDI_ICON_EVENT_ERROR            162
#define IDI_ICON_INFO_HARD              163
#define IDI_ICON_20CN                   164
#define IDI_ICON_INFO_IDIO              165
#define IDR_MENU_FILE_MANAGER           168
#define IDR_MENU_CLIENT_MANAGER         169
#define IDR_MENU_FILE_MANA              169
#define IDR_MENU_LIST                   170
#define IDR_MENU_LOG_LIST               170
#define IDD_DIALOG_CLIENT_TITLE         171
#define IDI_ICON_DOING                  186
#define IDI_ICON_FAIL                   187
#define IDI_ICON_WAIT                   188
#define IDI_ICON_INFO_NET               189
#define IDI_ICON_INFO_USER              190
#define IDI_ICON_FILE_TRANS             192
#define IDR_TOOLBAR_FILE                197
#define IDI_ICON_SUCCESS                201
#define IDR_MENU_FILE                   202
#define IDR_MENU_FILE_LIST              206
#define IDB_BITMAP1_HELP                220
#define IDB_BITMAP_HELP                 220
#define IDB_BITMAP_INDEX                221
#define IDB_BITMAP_MANA                 222
#define IDB_BITMAP_SETUP                223
#define IDB_BITMAP_DELETE               224
#define IDB_BITMAP_CREATE               225
#define IDB_BITMAP_TELNET               226
#define IDR_MENU_FILE_TRANS             229
#define IDI_ICON_SETUP                  232
#define IDR_TOOLBAR_FRAME               269
#define IDD_DIALOG_FRAMEWND             273
#define IDB_BITMAP_TEST                 274
#define IDB_BITMAP_FRAME                275
#define IDB_BITMAP_KEY                  279
#define IDB_BITMAP_MULT                 280
#define IDB_BITMAP_TLNT                 285
#define IDD_DIALOG_LOGIN                287
#define IDD_DIALOG_CLIENT_PROXY         288
#define IDB_BITMAP_REGEDIT              289
#define IDB_BITMAP_SERVICE              290
#define IDB_BITMAP_MULIT                291
#define IDB_BITMAP_PROC                 293
#define IDB_HDRDOWN                     296
#define IDB_HDRUP                       297
#define IDI_ICON_VIDEO                  298
#define IDC_EDIT_MAX_LINK_FILE          1000
#define IDC_EDIT_TEMP_PATH              1002
#define IDC_BUTTON_TEMP_DIR             1003
#define IDC_EDIT_PORT                   1004
#define IDC_EDIT_MAX_LINK_MAIN          1005
#define IDC_EDIT_PROCESS                1005
#define IDC_EDIT_PORT_FILE              1006
#define IDC_EDIT_START_FILE             1006
#define IDC_EDIT_CTRL_FILE              1007
#define IDC_EDIT_REGNAME                1008
#define IDC_SPIN_MAX_LINK_FILE          1009
#define IDC_EDIT_START_DLL              1009
#define IDC_COMBO_IPLIST                1010
#define IDC_SPIN_PORT_MAIN              1011
#define IDC_EDIT_CONTROL_DLL            1011
#define IDC_CHECK_ISICON                1012
#define IDC_SPIN_MAX_LINK_MAIN          1012
#define IDC_EDIT_USER_NAME              1013
#define IDC_STATIC_DDNS                 1014
#define IDC_SPIN_PORT_FILE              1014
#define IDC_BUTTON_CREATE               1016
#define IDC_EDIT_TITLE                  1017
#define IDC_EDIT_PORT_MAIN              1018
#define IDC_STATIC_LINE                 1020
#define IDC_STATIC_ANIMAL               1023
#define IDC_STATIC_20CN                 1024
#define IDC_STATIC_SANPARTY             1025
#define IDC_CHECK_ISLOCAL               1026
#define IDC_STATIC_TITLE                1029
#define IDC_BUTTON_MENU                 1030
#define IDC_LIST_USER                   1032
#define IDC_EDIT_TEXT                   1033
#define IDC_EDIT_SEND                   1036
#define IDC_STATIC_TITILE               1037
#define IDC_STATIC_CMD                  1038
#define IDC_EDIT_URL                    1040
#define IDC_CHECK_ISURL                 1042
#define IDC_COMBO_ISIE                  1043
#define IDC_EDIT_USER                   1044
#define IDC_EDIT_PASS                   1045
#define IDC_PROGRESS_SHOW               1046
#define IDC_RADIO_VIP                   1049
#define IDC_RADIO_NOVIP                 1050
#define IDC_COMBO_PROC                  1057
#define IDC_EDIT_BAK_URL                1058
#define ID_CLIENT_MANAGER               32771
#define ID_CLIENT_FRAME_CONTROL         32772
#define ID_CLIENT_CHAT                  32773
#define ID_GLOBAL_SETUP                 32774
#define ID_CLIENT_CREATE                32775
#define ID_SCAN_TOOL                    32776
#define ID_CLIENT_TITLE                 32777
#define ID_CLIENT_PRO_CLOSE             32778
#define ID_CLIENT_PRO_UNINSTALL         32779
#define ID_CLIENT_PC_SHUTDOWN           32780
#define ID_CLIENT_PC_RESTART            32781
#define ID_CLIENT_DELETE                32782
#define ID_ALIVE_HELP                   32783
#define ID_CLIENT_PUTIN                 32784
#define ID_ALL_CLIENT_PRO_CLOSE         32787
#define ID_ALL_CLIENT_PRO_UNINSTALL     32788
#define ID_ALL_CLIENT_PC_CLOSE          32789
#define ID_ALL_CLIENT_PC_RESTART        32790
#define ID_FIND_CLIENT_TITLE            32791
#define ID_FIND_CLIENT_NOTE             32792
#define ID_FILE_STOP_ALL_TRANS          32793
#define ID_FILE_START_ALL_TRANS         32794
#define ID_FILE_STOP                    32795
#define ID_FILE_START                   32796
#define ID_FILE_DELETE                  32797
#define ID_LIST_DELETE_ITEM             32798
#define ID_LIST_EMPTY_ITEM              32799
#define ID_LIST_FILE_TRANS              32800
#define ID_EMPTY_FILE_TRANS             32801
#define ID_MANAGE_LOG                   32802
#define ID_STOP_FILE_TRANS              32803
#define ID_START_FILE_TRANS             32804
#define ID_DELETE_FILE_TRANS            32806
#define ID_SAVE_LIST_LOG                32807
#define ID_TELNET_WND                   32808
#define ID_MENUITEM32809                32809
#define ID_TO_TOP                       32810
#define ID_TO_BOTTOM                    32811
#define ID_STARTMOUSE                   32812
#define ID_SAVEPIC                      32813
#define ID_FRAME_MONITOR                32814
#define ID_REG_CONTROL                  32815
#define ID_SERVICE_CTRL                 32816
#define ID_PROCESS_CTRL                 32817
#define ID_KEY_MONITOR                  32818
#define ID_MULT_MONITOR                 32819
#define ID_QUERY_FILE_TRANS             32820
#define ID_MONITORKEY                   32821
#define ID_TLNT                         32822
#define ID_MODIFY_TITLE                 32823
#define ID_CLIENT_FILE_MANAGER          32824
#define ID_REGEDIT                      32825
#define ID_PROC                         32826
#define ID_SERVICE                      32827
#define ID_MUILT                        32828
#define ID_CLIENT_PROXY                 32829
#define ID_CLIENT_LINK_COUNT            61204
#define ID_20CNLINK                     61205
#define ID_FILE_TRANS_COUNT             61206
#define ID_FRAME_SIZE                   61207

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        302
#define _APS_NEXT_COMMAND_VALUE         32830
#define _APS_NEXT_CONTROL_VALUE         1059
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
